'use client';
import {useCallback,useEffect,useState} from 'react';
import {customerFetch,getCustomer,CustomerProfile} from '@/lib/customer-api';
import CustomerAccountState from '@/components/CustomerAccountState';
export default function Profile(){
 const [data,setData]=useState<CustomerProfile|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [saved,setSaved]=useState(false);
 const load=useCallback(async()=>{try{setData(await getCustomer());setError('');}catch(e){setError((e as Error).message);}},[]);useEffect(()=>{void load();},[load]);
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setError('');setSaved(false);const form=new FormData(event.currentTarget);const delivery_address=Object.fromEntries(['line1','line2','city','region','postal_code'].map(k=>[k,String(form.get(k)||'')]));try{setData(await customerFetch<CustomerProfile>('me',{method:'PATCH',body:JSON.stringify({name:form.get('name'),phone:form.get('phone'),delivery_address})}));setSaved(true);}catch(e){if((e as {status?:number}).status===401)setData(null);setError((e as Error).message);}finally{setBusy(false);}}
 if(!data&&error)return <CustomerAccountState error={error} retry={load}/>;if(!data)return <p role="status">Loading contact details…</p>;
 return <><h1 className="text-3xl font-bold">Contact &amp; delivery</h1><p className="mt-3">These details apply to future requests. Existing order details stay as agreed.</p><form onSubmit={save} className="mt-7 max-w-xl space-y-4 rounded-xl border bg-white p-6"><p>Verified email: <strong>{data.normalized_email}</strong></p><p className="text-sm">To use a different email, <a className="underline" href="/account/sign-in">verify that email with a new sign-in link</a>. Existing requests stay with this account.</p>{[['name','Name'],['phone','Phone (optional)'],['line1','Delivery address'],['line2','Apartment / unit'],['city','City'],['region','State'],['postal_code','ZIP code']].map(([key,label])=><label className="block font-medium" key={key}>{label}<input name={key} defaultValue={key==='name'?data.name:key==='phone'?data.phone:data.delivery_address[key]||''} maxLength={key==='phone'?40:120} className="mt-1 min-h-11 w-full rounded-lg border px-3"/></label>)}<p className="text-sm text-zinc-600">Providing a phone number does not sign you up for texts. Delivery coverage and arrangements require confirmation.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}{saved&&<p role="status">Contact details saved.</p>}<button disabled={busy} className="min-h-12 rounded-lg bg-brand-700 px-5 font-bold text-white">{busy?'Saving…':'Save contact details'}</button></form></>;
}
