'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {customerFetch,getCustomer,submitCustomerRequest,CustomerProfile,CustomerRequest} from '@/lib/customer-api';
import CustomerAccountState from '@/components/CustomerAccountState';
export default function Account(){
 const [profile,setProfile]=useState<CustomerProfile|null>(null);const [requests,setRequests]=useState<CustomerRequest[]>([]);const [orders,setOrders]=useState<CustomerRequest[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const [me,r,o]=await Promise.all([getCustomer(),customerFetch<{requests:CustomerRequest[]}>('requests'),customerFetch<{orders:CustomerRequest[]}>('orders')]);setProfile(me);setRequests(r.requests);setOrders(o.orders);setError('');}catch(e){if((e as {status?:number}).status===401){setProfile(null);setRequests([]);setOrders([]);}setError((e as Error).message);}},[]);
 useEffect(()=>{void load();const refresh=()=>{if(!document.hidden)void load();};window.addEventListener('focus',refresh);return()=>window.removeEventListener('focus',refresh);},[load]);
 async function resume(){if(!profile?.pending_request||busy)return;setBusy(true);try{await submitCustomerRequest({...profile.pending_request,customer_email:profile.normalized_email});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function logout(){if(busy)return;setBusy(true);try{await customerFetch('logout',{method:'POST',body:'{}'});window.location.assign('/account/sign-in');}catch(e){setError((e as Error).message);setBusy(false);}}
 if(error&&!profile)return <CustomerAccountState error={error} retry={load}/>;
 if(!profile)return <p role="status">Loading My Junkerz…</p>;
 return <><div className="flex items-center justify-between gap-4"><div><h1 className="text-3xl font-bold">Your requests &amp; orders</h1><p className="mt-2 text-zinc-600">{profile.name||profile.normalized_email}</p></div><button onClick={logout} disabled={busy} className="min-h-11 rounded-lg border bg-white px-4">Sign out</button></div>{error&&<p role="alert" className="mt-5 text-red-700">{error}</p>}{profile.pending_request&&<section className="mt-8 rounded-xl border border-brand-200 bg-white p-6"><h2 className="text-xl font-bold">Your saved request</h2><p className="mt-2">{profile.pending_request.component||'Vehicle or part request'} · {profile.pending_request.customer_name}</p><p className="mt-2 text-sm">{profile.pending_request.target_vehicle}{profile.pending_request.message && ` · ${profile.pending_request.message}`}</p><p className="mt-2">Your email is verified. Send this request to ask Junkerz to confirm availability and fitment.</p><button disabled={busy} onClick={resume} className="mt-4 min-h-11 rounded-lg bg-brand-700 px-5 font-bold text-white">{busy?'Sending…':'Send saved request'}</button></section>}<History title="Requests" rows={requests}/><History title="Orders" rows={orders} orders/><p className="mt-8 text-sm text-zinc-600">Older requests stay private until you add them from their original request link while signed in with the same verified email.</p></>;
}
function History({title,rows,orders=false}:{title:string;rows:CustomerRequest[];orders?:boolean}){return <section className="mt-10"><h2 className="text-xl font-bold">{title}</h2>{rows.length?<ul className="mt-4 space-y-3">{rows.map(row=><li key={row.id}><Link href={orders?`/account/orders/${encodeURIComponent(row.order_id||'')}`:`/account/requests/${row.id}`} className="block rounded-xl border bg-white p-5 hover:border-brand-400"><div className="flex flex-wrap justify-between gap-2"><strong>{row.reference}</strong><span className="text-sm">{(orders?row.payment_status:row.status)?.replaceAll('_',' ')}</span></div><p className="mt-2">{row.component||row.vehicle_label}</p><p className="mt-2 text-sm text-zinc-600">{row.customer_message}</p></Link></li>)}</ul>:<p className="mt-4 rounded-xl border bg-white p-6">No {title.toLowerCase()} yet. <Link className="underline" href="/shop">Browse cars &amp; parts</Link>.</p>}</section>;}
